#!/command/with-contenv bash

bootstrap_filesystem() {
    mkdir -p "${UNIT_WEBROOT}"
    chown "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_WEBROOT}"
}

configure_nginx() {
    ### Perform Nginx reverse proxy modifications
    if var_true "${ENABLE_HTTPS_REVERSE_PROXY}" ; then
        sed -i "s|^fastcgi_param  HTTPS .*$|fastcgi_param  HTTPS 'on';|g" /etc/nginx/fastcgi_params
        PROTOCOL="https://"
    else
        print_warn "Disabling Nginx Reverse Proxy HTTPS Termination Support"
        sed -i "s|^fastcgi_param  HTTPS .*$|fastcgi_param  HTTPS 'off';|g" /etc/nginx/fastcgi_params
        PROTOCOL="http://"
    fi
}

create_bash_alias() {
    cat >> /root/.bashrc <<EOF
function wp-cli() {
      export oldpwd="\$(pwd)"
      cd ${UNIT_WEBROOT}
      sudo -u ${UNIT_USER} /usr/bin/wp-cli "\$@"
      cd "\${oldpwd}"
}
EOF
}

finalize_permissions() {
    if var_true "${UNIT_FORCE_RESET_PERMISSIONS}" ; then
        chown -R "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_WEBROOT}"
    fi
}

install_wordpress() {
    transform_file_var \
                    ADMIN_EMAIL \
                    ADMIN_USER \
                    ADMIN_PASS \
                    DB_HOST \
                    DB_PASS \
                    DB_PORT \
                    DB_PREFIX \
                    DB_USER

    case "${UPDATE_MODE,,}" in
        all | major | true | enable* | yes ) UPDATE_MODE=true ;;
        none | false | disable* | no ) UPDATE_MODE=false ;;
        minor ) UPDATE_MODE=minor ;;
    esac

    if [ ! -f "${UNIT_WEBROOT}"/wp-load.php ] ; then
        sanity_var ADMIN_EMAIL "Admin Email"
        sanity_var ADMIN_PASS "Admin Password"
        print_warn "Wordpress Installation not found, Downloading and setting up - Please wait 1-3 minutes.."
        cd "${UNIT_WEBROOT}"
        silent sudo -u "${UNIT_USER}" wp-cli core download --locale="${SITE_LOCALE}"
        silent sudo -u "${UNIT_USER}" wp-cli core config --dbhost="${DB_HOST}":"${DB_PORT}" --dbname="${DB_NAME}" --dbprefix="${DB_PREFIX}" --dbuser="${DB_USER}" --dbpass="${DB_PASS}" --dbcharset="${DB_CHARSET}"
        silent sudo -u "${UNIT_USER}" wp-cli core install --url="${PROTOCOL}""${SITE_URL}""${SITE_PORT}" --title="${SITE_TITLE}" --admin_user="${ADMIN_USER}" --admin_password="${ADMIN_PASS}" --admin_email="${ADMIN_EMAIL}" --skip-email
        sudo -u "${UNIT_USER}" chmod 644 wp-config.php

        ### Add URL information to allow for switching host/domainnames easily
        echo "define( 'WP_HOME', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" | silent sudo -u "${UNIT_USER}" tee -a "${UNIT_WEBROOT}"/wp-config.php
        echo "define( 'WP_SITEURL', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" | silent sudo -u "${UNIT_USER}" tee -a "${UNIT_WEBROOT}"/wp-config.php
        echo "define( 'WP_AUTO_UPDATE_CORE', '${UPDATE_MODE,,}' );" | silent sudo -u "${UNIT_USER}" tee -a "${UNIT_WEBROOT}"/wp-config.php
        silent rm -rf "${UNIT_WEBROOT}"/readme.html
        silent rm -rf "${UNIT_WEBROOT}"/license.txt
        silent rm -rf "${UNIT_WEBROOT}"/wp-content/plugins/hello.php
        silent chown -R "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_WEBROOT}"
    else
        if ! grep -c -q "'WP_HOME'" "${UNIT_WEBROOT}"/wp-config.php ; then
            echo "define( 'WP_HOME', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" | silent sudo -u "${UNIT_USER}" tee -a "${UNIT_WEBROOT}"/wp-config.php
        fi

        if ! grep -c -q "'WP_SITEURL'" "${UNIT_WEBROOT}"/wp-config.php ; then
            echo "define( 'WP_SITEURL', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );" | silent sudo -u "${UNIT_USER}" tee -a "${UNIT_WEBROOT}"/wp-config.php
        fi

        if ! grep -c -q "'WP_AUTO_UPDATE_CORE'" "${UNIT_WEBROOT}"/wp-config.php ; then
            echo "define( 'WP_AUTO_UPDATE_CORE', '${UPDATE_MODE,,}' );" | silent sudo -u "${UNIT_USER}" tee -a "${UNIT_WEBROOT}"/wp-config.php
        fi

        sed -i \
                    -e "s|define( 'DB_HOST', '.*' );|define( 'DB_HOST', '${DB_HOST}:${DB_PORT}' );|g" \
                    -e "s|define( 'DB_NAME', '.*' );|define( 'DB_NAME', '${DB_NAME}' );|g" \
                    -e "s|define( 'DB_USER', '.*' );|define( 'DB_USER', '${DB_USER}' );|g" \
                    -e "s|define( 'DB_PASSWORD', '.*' );|define( 'DB_PASSWORD', '${DB_PASS}' );|g" \
                    -e "s|define( 'DB_CHARSET', '.*' );|define( 'DB_CHARSET', '${DB_CHARSET}' );|g" \
                "${UNIT_WEBROOT}"/wp-config.php

        if var_true "${ROTATE_KEYS}" ; then
            print_notice "Rotating Secrets and Keys"
            silent sudo -u "${UNIT_USER}" wp-cli config shuffle-salts --config-file="${UNIT_WEBROOT}"/wp-config.php
        fi

        wpoldurl=$(grep "WP_HOME" "${UNIT_WEBROOT}"/wp-config.php | cut -d \' -f 4)
        if [ "$wpoldurl" != "${PROTOCOL}${SITE_URL}${SITE_PORT}" ]; then
            if [ "${SITE_URL_UPDATE_MODE,,}" = "all" ] || [ "${SITE_URL_UPDATE_MODE,,}" = "file" ]; then
                print_notice "Modifying wordpress to serve from ${wpoldurl} to ${PROTOCOL}${SITE_URL}${SITE_PORT} in wp-config.php"
                sed -i \
                            -e "s|define( 'WP_HOME', '.*' );|define( 'WP_HOME', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );|g" \
                            -e "s|define( 'WP_SITEURL', '.*' );|define( 'WP_SITEURL', '${PROTOCOL}${SITE_URL}${SITE_PORT}' );|g" \
                        "${UNIT_WEBROOT}"/wp-config.php
            fi
            if [ "${SITE_URL_UPDATE_MODE,,}" = "all" ] || [ "${SITE_URL_UPDATE_MODE,,}" = "db" ]; then
                print_notice "Modifying wordpress to serve from ${wpoldurl} to ${PROTOCOL}${SITE_URL}${SITE_PORT} in database"
                silent sudo -u "${UNIT_USER}" wp-cli search-replace "${wpoldurl}" "${PROTOCOL}${SITE_URL}${SITE_PORT}" --skip-columns=guid --path="${UNIT_WEBROOT}"
            fi
        fi
    fi
}
