#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="wordpress"

sanity_db mariadb
db_ready mariadb
sanity_var SITE_URL "Site URL"
_wordpress_bootstrap_filesystem
_wordpress_configure_unit
_wordpress_install_wordpress
_wordpress_create_bash_alias
_wordpress_finalize_permissions
print_info "Wordpress Initialization Complete, now starting webserver and PHP engine"

liftoff
