#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-nginx ]; then

  ### Make sure that DB is accessible
  while true; do
    mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
    out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
    echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
    if [ $? -eq 0 ]; then
      echo "[maridb] Server is up !"
      break
    fi
    echo "[mariadb] Server "$DB_HOST" is not available. Retying in 2 seconds"
    sleep 2
  done


### Check to see if this is a new install, if yes download Wordpress and other pieces...
if [ ! -f /www/wordpress/index.php ] ; then
   echo "** Wordpress Not Found, Downloading and setting up......"
   cd /tmp
   curl -O https://wordpress.org/latest.tar.gz
   tar xvfz /tmp/latest.tar.gz -C /www/ --overwrite  > /dev/null
   rm -rf latest.tar.gz
   echo "** Insalled... Please visit the website and enter in DB Credentials"
   rm -rf /www/wordpress/readme.html
   rm -rf /www/wordpress/license.txt
   rm -rf /www/wordpress/wp-content/plugins/hello.php
   chown nginx:www-data /www/wordpress
fi

### Force Reset Permissions for Security
  chown -R nginx:www-data /www/wordpress

## Start nginx
  mkdir -p /www/logs/nginx
  mkdir -p /tmp/nginx
  chown -R nginx /www/logs/nginx
  chown nginx /tmp/nginx
  mkdir -p /tmp/state
  echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** Starting nginx'
exec nginx
